blog/config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
    
  
  resources :posts do
    resources :comments
  end
    root "posts#index"

end

blog/app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

blog/app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

blog/app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :user
	belongs_to :post
	validates :comment, presence: true, length: { minimum: 2, maximum: 200 }

end

blog/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { in: 3..20 }, :uniqueness => {alert: "Already Exixts" }
	validates :content, presence: true
end

blog/app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  
  
  protect_from_forgery with: :exception
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	# http_basic_authenticate_with name:"susantas", passwor: "mindfire", only: :destroy

	before_action :find_posts, only: [:create,:destroy]
	before_action :authenticate_user!
	def create
		@comment = @post.comments.create(params[:comment].permit(:comment))
		if @comment.valid?

			@comment.user_id = current_user.id
			if @comment.save
				redirect_to post_path(@post)
			else
				render nothing: true
			end
		else
			redirect_to post_path(@post), :alert => 'Comment must be within 2-200 characters.'
		end
	end

	def destroy
		# @post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
 		@comment.destroy
		redirect_to post_path(@post)
	end

	private
		
	def find_posts
		@post = Post.find(params[:post_id]) 
	end

end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

	# http_basic_authenticate_with name: "susantas", password: "mindfire",
	# except: [:index, :show]
	
	before_action :find_post, only: [:update, :edit, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	rescue_from ActiveRecord::RecordNotFound, with: :record_not_found


	def index
		@posts = Post.all.order(created_at: :DESC)
	end

	def new
		@post = current_user.posts.new
	end	

	def create
		@post = current_user.posts.new(post_params)
		if @post.save
			redirect_to @post, :notice => "Post Saved Successfully"
		else
			render 'new'
		end
	end

	def show
		render locals: {
			post: Post.find_by!(id: params[:id])
		}
	end

	def edit
		
	end

	def update
		if @post.update(post_params)
			redirect_to @post, :notice => "Post Updated Successfully"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path, :notice => "Post Removed Successfully"
	end

	private

	def post_params
		params.require(:post).permit(:title, :content)
	end

	def find_post
		@post = Post.find_by!(id: params[:id])
	# rescue
	# 	post_not_found
	end

	def record_not_found
      render plain: "404 Not Found", status: 404
    end

end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/views/comments/_comment.html.erb
<div class="box">
	<article class="media">
		<div class="media-content">
			<div class="content">
				<p>
					<strong>
						<%= comment.user.email %>
					</strong>:&nbsp;

					<%= comment.comment %>
				</p>
				
			</div>
		</div>
		<% if comment.user == current_user || post.user == current_user %>
		<%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button is-danger", data: { confirm: "Are you sure?"} %>
		<% end %>
	</article>
</div>

blog/app/views/comments/_form.html.erb
<%= form_for([post, comment =  post.comments.build]) do |f| %>
	
	<% if comment.errors.any? %>
		<div id="error_explanation" class="alert" style="text-align: center; color: red;">
			<h2><%= pluralize(comment.errors.count, "error") %> Prohibited this comment from being saved:</h2>

			<ul>
				<% comment.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="field">
		<div class="control">
			<%= f.label :comment, class: 'label' %>
			<%= f.cktext_area :comment, class: 'textarea', wrapper: false %>
		</div>
	</div>
	<%= f.submit :Submit, class: "button is-primary" %>

<% end %> 

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="font-family: times new roman; ">
	<section class="hero is-primary is-small">
		<div class="hero-head">
			<nav class="navbar is-transparent">
			  <div class="contailer">
			  	<div class="navbar-brand">
			  		<%= link_to 'Blog', root_path, class:"navbar-item" %>
		  		</div>
			  </div>

			  <div id="navbarBasicExample" class="navbar-menu">
			    <div class="navbar-start">
			      

			      <%= link_to "Create New Post", new_post_path, class:"navbar-item" %>

			    </div>

			    <div class="navbar-end">
			      <div class="navbar-item">
			        <div class="buttons">
			        	<% if user_signed_in? %>
			        		<div class="button is-danger">
			        			<strong><%= link_to 'Logout', destroy_user_session_path, method: :delete %></strong>
			        		</div>
			        	<% else %>
				          <div class="button is-warning">
				            <strong><%= link_to 'Sign up', new_user_registration_path, class:"navbar-item" %></strong>
				          </div>
				          <div class="button is-info">
				            <%= link_to 'Login', new_user_session_path, class:"navbar-item" %>
				          </div>
			          	<% end %>
			        </div>
			      </div>
			    </div>
			  </div>
			</nav>
		</div>

		<div class="hero-body">

			<div class="container has-text-centered">

				<h1 class="title">
					<%= yield :page_title %>
				</h1>
				
			</div>
		</div>


	</section>
	
	<!-- <div style="color: green; text-align: center;">
		<% flash.each do |key, value| %>
			<p><%= value %></p>
		<% end %>	
	</div> -->
<div class="clear-fix"><br></div>
	<section>
		

		<div class="clearfix"></div>
		<div>
			<p class="notice" style="color: green; margin-left: 40% ;"><%= notice %></p>
	   		<p class="alert" style="color: red; margin-left: 40%;"><%= alert %></p>
	   	</div>
	   	<div>

	   		<%= yield %>	
	   	</div>
	   	
	</section>		

</body>
</html>

blog/app/views/posts/_form.html.erb
<div class="section">
	<%= form_for post do |f| %>

	<% if post.errors.any? %>
		<div id="error_explanation" class="alert" style="text-align: center; color: red;">
			<h2><%= pluralize(post.errors.count, "error") %> Prohibited this post from being saved:</h2>

			<ul>
				<% post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
			</ul>
		</div>
	<% end %>


	<div class="field">
		<div class="control">
			
			<%= f.label :title, class: 'label', wrapper: false %>
			<%= f.text_field :title, class: 'input', wrapper: false %>
		</div>
	</div>
	<div class="field">
		<div class="control">
			<%= f.label :content, class: 'label' %>
			<%= f.cktext_area :content,class: 'textarea', wrapper: false  %>
		</div>
	</div>
	
	<%= f.submit :Save, class: "button is-primary" %>
	<% end %>
</div>

blog/app/views/posts/edit.html.erb
<% content_for :page_title, "Edit Post" %>

<%= render 'form', post: @post %>

blog/app/views/posts/index.html.erb
<% content_for :page_title, "Index" %>

<div class="tile is-ancestor" style=" width: 20%; height: 350px; float: left; margin-left: 0%;">
  <div class="tile is-parent">
    <article class="tile is-child notification is-info">
      <div class="content" style="text-align: center;">
        <div class="title" style="font-size: 17px; font-variant: small-caps;"><u>TAGS</u></div>
        <p class="subtitle" style="font-variant: small-caps;">
        	<ul style="text-align: left;">
        		<li>Educational</li>
				<li>Technical</li>
				<li>Life Stories</li>
				<li>Devotional</li>
        	</ul>
        	
        </p>
        <div class="content">
        </div>
      </div>
    </article>
  </div>
</div>

<section class="section">
	<div class="container" style="width: 60%;">
		<% @posts.each do |post| %>
		<div class="card">
			<div class="card-content">
				<div class="media">
					<div class="media-content">
						<p class="title is-4">
							<%= link_to post.title, post %>
						</p>
					</div>
				</div>
				<div class="content" style="overflow: hidden; height: auto;">
					<strong>Posted By:</strong>&nbsp; <%= post.user.email.split('@')[0].capitalize %><br />
					<strong>Posted At:</strong>&nbsp; <%= post.created_at.strftime("%I:%M %p") %>
				</div>
			</div>
		</div>
	<% end %>
	</div>
</section>

blog/app/views/posts/new.html.erb
<% content_for :page_title, "Create New Post" %>

<%= render 'form', post: @post %>

blog/app/views/posts/show.html.erb
<% content_for :page_title, post.title %>



<section class="section">
	<div class="container">
		<nav class="level">
			<div class="level-left">
				<p class="level-item">
					<strong>Actions</strong>
				</p>
			</div>
		<% if post.user == current_user %>
			<div class="level-right">
				<p class="level-item">
					<%= link_to "Edit",edit_post_path(post),class: "button" %>

				</p>
				<p class="level-item">
					<%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: "Are you sure?"}, class: "button is-danger " %>
				</p>
			</div>
		<% end %>	

		</nav>
		<hr />

		<div class="content">
			<h6>Created on: </h6><%= post.created_at.strftime("%b %d, %Y") %>
			<p><h5>Contents :</h5><%= raw post.content %></p>
			
		</div>
</section>

<section class="section comments">
	<div class="container">
		<h2 class="subtitle is-5">
			<strong><%= post.comments.count %>
				
			</strong> Comments
		</h2>
		<%= render post.comments, post: post%>
		<div class="comment-form">
			<hr />
			<h3 class="subtitle is-3">Leave a reply</h3>
			<%= render 'comments/form', post: post %>
		</div>
	</div>
</section>